export const palette = {
  light: {
    page: '#f0f2f5',
    sidebarBg: '#ffffff',
    sidebarBorder: '#E5E7EB',
    chatBg: '#efeae2',
    assistantBubble: '#ffffff',
    assistantBorder: '#E5E7EB',
    userBubble: '#d9fdd3',
    userBorder: '#c4ecbe',
    composerBg: '#f0f2f5',
    composerBorder: '#E5E7EB',
    headerBg: '#ffffff',
    headerBorder: '#E5E7EB',
    text: '#111827',
    textMuted: '#6B7280',
    accent: '#6366F1',
    sent: '#059669',
    popoverBg: '#ffffff',
    popoverBorder: '#E5E7EB',
  },
  dark: {
    page: '#0B0B0F',
    sidebarBg: '#14141A',
    sidebarBorder: '#2A2A33',
    chatBg: '#0D0F12',
    assistantBubble: '#1F2229',
    assistantBorder: '#2A2A33',
    userBubble: '#055d3e',
    userBorder: '#0a7a51',
    composerBg: '#14141A',
    composerBorder: '#2A2A33',
    headerBg: '#14141A',
    headerBorder: '#2A2A33',
    text: '#F3F4F6',
    textMuted: '#9CA3AF',
    accent: '#A5B4FC',
    sent: '#34D399',
    popoverBg: '#14141A',
    popoverBorder: '#2A2A33',
  },
} as const;

export type Palette = { [K in keyof typeof palette.light]: string };
export const pick = (dark: boolean): Palette => (dark ? palette.dark : palette.light);
